#!/usr/bin/env python3
"""Dump CoolProp humid-air ground truth into a committed JSON reference.

Why this exists
---------------
`props/psychro.rs` and the `Enthalpy/WetBulb(AirH2O, …)` call sites need a
humid-air backend at CoolProp accuracy (measured: an ideal-gas ASHRAE model is
2.4e-4 off on `(T,W)` and 2.7e-3 off on `(T,R)`, the latter because converting
relative humidity needs the enhancement factor `f(T,P)`, not bare `p_ws`).
Implementing ASHRAE RP-1485 is only safe if every step can be graded, and CI
has no `libCoolProp`. So the truth is recorded here once, from the same
vendored library the golden-dumper uses, and the Rust tests grade against it.

This mirrors `tools/table-gen` / `tools/aux-gen`: generated artefact, version
stamped, regenerated deliberately rather than on every build.

    python3 tools/humidair-ref/gen.py > fixtures/humidair/reference.json
"""
import ctypes, json, sys, pathlib

# The reference repo is a *sibling* of this one, in either spelling — the rule
# tools/frees-home.sh already encodes. parents[2] is this repo's root, so the
# sibling is one level above that.
_SIBLINGS = pathlib.Path(__file__).resolve().parents[2].parent
SO = next(
    (p for p in (_SIBLINGS / s / "backend/core/native/libCoolProp.so"
                 for s in ("frees", "frEES")) if p.exists()),
    None,
)
if SO is None:
    sys.exit(f"libCoolProp.so not found beside this repo (looked in {_SIBLINGS}/frees|frEES)")

lib = ctypes.CDLL(str(SO))
lib.HAPropsSI.restype = ctypes.c_double
lib.HAPropsSI.argtypes = [ctypes.c_char_p] + [ctypes.c_char_p, ctypes.c_double] * 3
lib.PropsSI.restype = ctypes.c_double
lib.PropsSI.argtypes = [ctypes.c_char_p, ctypes.c_char_p, ctypes.c_double,
                        ctypes.c_char_p, ctypes.c_double, ctypes.c_char_p]
lib.get_global_param_string.argtypes = [ctypes.c_char_p, ctypes.c_char_p, ctypes.c_int]


def ha(out, n1, v1, n2, v2, n3, v3):
    return lib.HAPropsSI(out.encode(), n1.encode(), ctypes.c_double(v1),
                         n2.encode(), ctypes.c_double(v2), n3.encode(), ctypes.c_double(v3))


def version():
    buf = ctypes.create_string_buffer(2048)
    lib.get_global_param_string(b"version", buf, 2048)
    return buf.value.decode()


def finite(x):
    return isinstance(x, float) and x == x and abs(x) != float("inf")


def main():
    # The band the pending fixtures live in: near-ambient HVAC psychrometrics.
    temps = [273.15, 278.15, 283.15, 288.15, 293.15, 295.0, 297.15, 300.0,
             303.15, 305.0, 308.15, 313.15, 318.15, 323.15]
    pressures = [95000.0, 101325.0, 105000.0]

    cases = {"psat_water": [], "w_saturated": [], "h_from_tw": [],
             "h_from_tr": [], "h_from_tb": [], "b_from_th": []}

    for T in temps:
        # IAPWS-95 saturation pressure — the base of the enhancement factor.
        p = lib.PropsSI(b"P", b"T", ctypes.c_double(T), b"Q", ctypes.c_double(0.0), b"Water")
        if finite(p):
            cases["psat_water"].append({"T": T, "p_ws": p})

    for P in pressures:
        for T in temps:
            # Saturated humidity ratio: back-solves to the enhancement factor,
            # W_sat = 0.621945 * f*p_ws / (P - f*p_ws).
            w = ha("W", "T", T, "R", 1.0, "P", P)
            if finite(w):
                cases["w_saturated"].append({"T": T, "P": P, "W": w})
            for W in (0.0, 0.002, 0.005, 0.009, 0.010, 0.016, 0.020):
                h = ha("H", "T", T, "W", W, "P", P)
                if finite(h):
                    cases["h_from_tw"].append({"T": T, "P": P, "W": W, "H": h})
            for R in (0.0, 0.2, 0.45, 0.5, 0.6, 0.8, 1.0):
                h = ha("H", "T", T, "R", R, "P", P)
                if finite(h):
                    cases["h_from_tr"].append({"T": T, "P": P, "R": R, "H": h})
            for dwb in (0.0, 2.0, 5.0, 8.0):
                B = T - dwb
                h = ha("H", "T", T, "B", B, "P", P)
                if finite(h):
                    cases["h_from_tb"].append({"T": T, "P": P, "B": B, "H": h})
            for W in (0.002, 0.009, 0.016):
                h = ha("H", "T", T, "W", W, "P", P)
                if not finite(h):
                    continue
                b = ha("B", "T", T, "H", h, "P", P)
                if finite(b):
                    cases["b_from_th"].append({"T": T, "P": P, "H": h, "B": b})

    out = {
        "_README": [
            "CoolProp humid-air ground truth. Generated by tools/humidair-ref/gen.py",
            "from the vendored libCoolProp the golden-dumper also uses.",
            "Regenerate deliberately; do not edit by hand.",
            "Consumed by crates/frees-core/src/props/humidair.rs tests, which have",
            "no libCoolProp available in CI.",
        ],
        "coolprop_version": version(),
        "cases": cases,
    }
    json.dump(out, sys.stdout, indent=1, sort_keys=True)
    sys.stdout.write("\n")
    for k, v in cases.items():
        print(f"  {k}: {len(v)} points", file=sys.stderr)


if __name__ == "__main__":
    main()
