// GENERATED FILE - DO NOT EDIT DIRECTLY.
// Compiled by scripts/compile-docs.js (npm run compile-docs). Small id/label
// lists for the main bundle: the Spotlight palette's Documentation group and
// the editor's F1 contextual help. The full content stays in the code-split
// /help route.

export const DOCS_TOPICS: { id: string; label: string }[] = [
  { id: `calculus`, label: `Numerical Integration (ODEs & Calculus)` },
  { id: `dynamic-ode`, label: `Transient / ODE Systems (DYNAMIC)` },
  { id: `optimization`, label: `Optimization & Parametric Sweeps` },
  { id: `debugging`, label: `Debugging a Solve` },
  { id: `errors`, label: `Errors & Diagnostics Index` },
  { id: `api`, label: `Solver Reference & API` },
  { id: `arch-async`, label: `How a Solve Runs` },
  { id: `arch-api`, label: `The REST API` },
  { id: `deploy-docker`, label: `Run Locally with Docker` },
  { id: `deploy-railway`, label: `Deploy to Railway` },
  { id: `deploy-health`, label: `Health & Scaling` },
  { id: `comp-first-network`, label: `Your First Component Network` },
  { id: `comp-connections`, label: `Connections & Junctions` },
  { id: `comp-schematic`, label: `Reading the Schematic` },
  { id: `comp-domains`, label: `Domains & Fluid Families` },
  { id: `comp-library`, label: `The Component Library` },
  { id: `comp-variants`, label: `Fidelity Variants (model$)` },
  { id: `comp-authoring`, label: `Writing Your Own Component` },
  { id: `comp-transient`, label: `Steady ↔ Transient from One Network` },
  { id: `comp-linearize`, label: `From Plant to Controller (LINEARIZE)` },
  { id: `comp-cycle-plots`, label: `Cycle Plots & Diagnostics` },
  { id: `comp-wizard`, label: `The Component Wizard` },
  { id: `comp-troubleshooting`, label: `Troubleshooting Networks` },
  { id: `plot-code`, label: `Plots in Code (PLOT)` },
  { id: `thermo`, label: `Thermophysical Properties Reference (CoolProp & Gas)` },
  { id: `solid-materials`, label: `Solid Material Properties Reference` },
  { id: `chemistry`, label: `Chemistry & Combustion` },
  { id: `humidair`, label: `Psychrometrics (AirH2O / Humid Air)` },
  { id: `state-tables`, label: `Fluid State Tables (STATE TABLE)` },
  { id: `gs-first-solve`, label: `1. Your First Solve` },
  { id: `gs-declarative`, label: `2. Thinking Declaratively` },
  { id: `gs-units-check`, label: `3. Units & Checking the Model` },
  { id: `gs-plots`, label: `4. See It: Tables & Plots` },
  { id: `gs-repl`, label: `5. Ask Questions: the REPL` },
  { id: `gs-components`, label: `6. Wire Components` },
  { id: `gs-next`, label: `7. Where to Go Next` },
  { id: `repl`, label: `REPL Terminal & Workspace` },
  { id: `shortcuts`, label: `Keyboard Shortcuts` },
  { id: `reports`, label: `Notes & Narrative` },
  { id: `digitizer-fit`, label: `Graph Digitizer & Curve Fit` },
  { id: `syntax`, label: `Equation Syntax & Rules` },
  { id: `math-funcs`, label: `Mathematical Functions` },
  { id: `special-funcs`, label: `Special & Statistical Functions` },
  { id: `variables`, label: `Variables, Guesses & Bounds` },
  { id: `uncertainty`, label: `Uncertainty Propagation` },
  { id: `units`, label: `Units & Dimensional Consistency` },
  { id: `arrays`, label: `Arrays & For Loops` },
  { id: `complex`, label: `Complex Numbers` },
  { id: `strings`, label: `String Variables & Functions` },
  { id: `matrices-decl`, label: `Declaring Matrices & Vectors` },
  { id: `matrices-ops`, label: `Matrix Operators` },
  { id: `matrices-blas`, label: `OpenBLAS Algebra Functions` },
  { id: `matrices-sys`, label: `Linear Systems & Decomposition` },
  { id: `functions`, label: `Custom Functions & Procedures` },
  { id: `tables-code`, label: `Custom Tables (TABLE)` },
  { id: `lookup-tables`, label: `Lookup Tables & Interpolation` },
  { id: `table-accessors`, label: `Table Accessors & Aggregates` },
  { id: `modules`, label: `Modular Submodels (MODULE)` },
  { id: `symbolic-cas`, label: `Control Systems & Symbolic CAS` },
  { id: `tut-msd`, label: `Tutorial: Mass–Spring–Damper, from Time Domain to Bode Plot` },
  { id: `tut-coil`, label: `Tutorial: Psychrometric Analysis of an AC Cooling Coil` },
  { id: `tut-rlc`, label: `Tutorial: Frequency Response of an RLC Filter` },
  { id: `tut-vccycle`, label: `Tutorial: A Refrigeration Cycle with Real Uncertainty` },
  { id: `tut-pump`, label: `Tutorial: Pump Selection from a Manufacturer's Curve` },
  { id: `verification`, label: `Verification Suite` }
];

export const REFERENCE_SLUGS: string[] = [
  `isa_p`,
  `isa_rho`,
  `isa_t`,
  `differentiate`,
  `gaussintegral`,
  `integral`,
  `uncertaintyof`,
  `apart`,
  `cancel`,
  `collect`,
  `denominator`,
  `diff`,
  `expand`,
  `factor`,
  `ilaplace`,
  `integrate`,
  `inverselaplace`,
  `laplace`,
  `numerator`,
  `simplify`,
  `together`,
  `adiabaticflametemp`,
  `adiabaticflametempeq`,
  `eq_molefraction`,
  `mix_conductivity`,
  `mix_cp`,
  `mix_enthalpy`,
  `mix_entropy`,
  `mix_mw`,
  `mix_viscosity`,
  `wiebe`,
  `wiebe_rate`,
  `angle`,
  `angledeg`,
  `cis`,
  `conj`,
  `imag`,
  `magnitude`,
  `real`,
  `aircoil`,
  `chiller`,
  `exv`,
  `exvcmd`,
  `heatercore`,
  `radiator`,
  `txv`,
  `pithermostat`,
  `battery`,
  `battery2rc`,
  `batterycellmap`,
  `batterypack`,
  `batteryrc`,
  `batterythermal`,
  `batterytransient`,
  `capacitor`,
  `chargercccv`,
  `currentsource`,
  `dcdcconverter`,
  `dcmotor`,
  `diode`,
  `electrolyzer`,
  `electrolyzerthermal`,
  `fuelcellstack`,
  `fuelcellstackcooled`,
  `ground`,
  `harnessresistance`,
  `heatingresistor`,
  `inductor`,
  `inverterloss`,
  `motormap`,
  `mpptblock`,
  `pmsm`,
  `pvsinglediode`,
  `resistor`,
  `solararray`,
  `supercapacitor`,
  `thermalfuse`,
  `voltagesource`,
  `accumulator`,
  `atmospheresource`,
  `boiler`,
  `combustor`,
  `combustorspecies`,
  `compressor`,
  `compressormap`,
  `condenser`,
  `duct`,
  `expansionvalve`,
  `fan`,
  `fancurve`,
  `fanmap`,
  `flowsensor`,
  `heatedduct`,
  `heatexchanger`,
  `mixer`,
  `nozzle`,
  `pipe`,
  `propeller`,
  `pump`,
  `pumpmap`,
  `regenerator`,
  `sink`,
  `source`,
  `splitter`,
  `throttle`,
  `turbine`,
  `turbocharger`,
  `twozonehx`,
  `valve`,
  `celltopackthermal`,
  `conduction`,
  `contactresistance`,
  `convection`,
  `heatpipe`,
  `heatsource`,
  `massgen`,
  `multizonewall`,
  `pcmmass`,
  `peltiertec`,
  `radiation`,
  `radiationtwosurface`,
  `thermalmass`,
  `thermalsensor`,
  `thermalsource`,
  `thermalswitch`,
  `wallrc`,
  `counterbalancevalve`,
  `hydraulicaccumulator`,
  `hydrauliccheckvalve`,
  `hydrauliccylinder`,
  `hydraulicdoubleactingcylinder`,
  `hydraulicflowcontrol`,
  `hydraulicflowdivider`,
  `hydraulicmotor`,
  `hydraulicorifice`,
  `hydraulicpilotcheckvalve`,
  `hydraulicpipe`,
  `hydraulicpump`,
  `hydraulicresistance`,
  `hydraulicsequencevalve`,
  `hydraulicsupply`,
  `hydraulictank`,
  `hydraulicthermalvolume`,
  `hydraulicvalve`,
  `hydraulicvalvecmd`,
  `hydraulicvolume`,
  `loadsensingpump`,
  `reliefvalve`,
  `servovalvedynamic`,
  `coolingtower`,
  `gravitydrain`,
  `hydroturbine`,
  `icestoragebrine`,
  `liquidcheckvalve`,
  `liquidcoldplate`,
  `liquidexpansiontank`,
  `liquidmixer`,
  `liquidorifice`,
  `liquidpipe`,
  `liquidpump`,
  `liquidpumpmap`,
  `liquidsink`,
  `liquidsource`,
  `liquidtank`,
  `liquidthermostat`,
  `liquidthreewayvalve`,
  `liquidvolume`,
  `liquidwallhx`,
  `opentank`,
  `thermalstoragetank`,
  `beltdrive`,
  `brake`,
  `cam`,
  `camfollower`,
  `clutch`,
  `clutchcmd`,
  `endstop`,
  `forcesource`,
  `freewheel`,
  `friction`,
  `gear`,
  `inertia`,
  `lever`,
  `mechground`,
  `planetary`,
  `rackpinion`,
  `rotationaldamper`,
  `rotationalspring`,
  `screwdrive`,
  `speedsource`,
  `torquesource`,
  `torsionalbacklash`,
  `transdamper`,
  `transground`,
  `transmass`,
  `transspring`,
  `wheelbrakethermal`,
  `ahu`,
  `airfilter`,
  `cabinzone`,
  `coolingcoil`,
  `diffuser`,
  `enthalpywheel`,
  `evaporativecooler`,
  `heatingcoil`,
  `humidifier`,
  `infiltration`,
  `membranehumidifier`,
  `mixingbox`,
  `moistairdamper`,
  `moistairduct`,
  `moistairfan`,
  `moistairsink`,
  `moistairsource`,
  `moistairwallhx`,
  `vavbox`,
  `anoderecirc`,
  `gasmixer`,
  `gasmixern`,
  `gaspipe`,
  `gassource`,
  `pneumaticactuator`,
  `pneumaticatmosphere`,
  `pneumaticcheckvalve`,
  `pneumaticdoubleactingcylinder`,
  `pneumaticorifice`,
  `pneumaticservovalve`,
  `pneumaticservovalvecmd`,
  `pneumaticsupply`,
  `pneumaticthermalvolume`,
  `pneumaticvalve32`,
  `pneumaticvalve52`,
  `pneumaticvolume`,
  `vacuumejector`,
  `automatictransmission`,
  `catalystlightoff`,
  `differential`,
  `drivecyclesource`,
  `engine`,
  `exhaustpipethermal`,
  `gearboxscheduled`,
  `gradeprofile`,
  `graderoadload`,
  `hybridpowersplit`,
  `meanvalueengine`,
  `quartercar`,
  `roadload`,
  `tirelongitudinal`,
  `tirepacejka`,
  `torqueconverter`,
  `transmission`,
  `vehiclebody`,
  `windrotor`,
  `sigabs`,
  `sigbias`,
  `sigconstant`,
  `sigdeadband`,
  `sigderivative`,
  `sigdiff`,
  `sigdivide`,
  `sigfirstorder`,
  `siggain`,
  `sigintegrator`,
  `sigleadlag`,
  `sigmap`,
  `sigmap2`,
  `sigmax`,
  `sigmin`,
  `sigpid`,
  `sigproduct`,
  `sigpulse`,
  `sigramp`,
  `sigratelimiter`,
  `sigrelay`,
  `sigsaturation`,
  `sigsecondorder`,
  `sigsine`,
  `sigspeedprobe`,
  `sigstep`,
  `sigsum`,
  `sigswitch`,
  `sigtable`,
  `sigthermalprobe`,
  `sigtime`,
  `sigvelprobe`,
  `supervisoryecms`,
  `zoneco2`,
  `blendmixer`,
  `blendsensor`,
  `blendsink`,
  `blendsource`,
  `boilingvessel`,
  `capillarytube`,
  `ejectormomentum`,
  `fewcellcondenser`,
  `fewcellevaporator`,
  `flashtank`,
  `gascooler`,
  `movingboundarycondenser`,
  `movingboundaryevaporator`,
  `oilseparator`,
  `proportionalreliefvalve`,
  `reversingvalve`,
  `steamreliefvalve`,
  `suctionaccumulator`,
  `threezonehx`,
  `transcriticalbackpressurevalve`,
  `twophasecap`,
  `twophasechamber`,
  `twophasecompressor`,
  `twophasecondenser`,
  `twophasecondenserfloat`,
  `twophasecondenserua`,
  `twophaseejector`,
  `twophaseenthalpysource`,
  `twophaseevaporator`,
  `twophaseevaporatorua`,
  `twophaseexpansionvalve`,
  `twophaseflowres`,
  `twophaseinternalhx`,
  `twophaseinventory`,
  `twophasemixer`,
  `twophaseoilrider`,
  `twophasepipe`,
  `twophasepressuresink`,
  `twophasepressuresource`,
  `twophasereceiver`,
  `twophasesensor`,
  `twophaseshorttube`,
  `twophasesink`,
  `twophasesource`,
  `twophasesourceph`,
  `twophasevolume`,
  `txvsuperheat`,
  `a_astar`,
  `beta_oblique`,
  `fanno_fld`,
  `fanno_p_pstar`,
  `fanno_p0_p0star`,
  `fanno_t_tstar`,
  `m2_shock`,
  `mach_a_astar`,
  `mach_prandtlmeyer`,
  `machangle`,
  `p0_p`,
  `p02_p01_shock`,
  `p2_p1_shock`,
  `prandtlmeyer`,
  `rayleigh_p_pstar`,
  `rayleigh_p0_p0star`,
  `rayleigh_t_tstar`,
  `rayleigh_t0_t0star`,
  `rho0_rho`,
  `rho2_rho1_shock`,
  `stagnationpres`,
  `stagnationtemp`,
  `t0_t`,
  `t2_t1_shock`,
  `theta_oblique`,
  `acker`,
  `balreal`,
  `bode`,
  `c2d`,
  `ctrb`,
  `d2c`,
  `dare`,
  `dlqr`,
  `dlyap`,
  `errorconst`,
  `feedback`,
  `gram`,
  `impulse`,
  `lqe`,
  `lqr`,
  `lsim`,
  `lyap`,
  `margin`,
  `mason`,
  `nichols`,
  `nyquist`,
  `obsv`,
  `pade`,
  `parallel`,
  `pidtune`,
  `place`,
  `pole`,
  `residue`,
  `rlocus`,
  `routh`,
  `series`,
  `ss`,
  `ss2ss`,
  `ss2tf`,
  `step`,
  `stepinfo`,
  `tf`,
  `tf2ss`,
  `tf2zp`,
  `zero`,
  `zp2tf`,
  `designing a controller (pid & lqr)`,
  `ev thermal-management system`,
  `frequency-domain stability analysis`,
  `rankine steam power cycle`,
  `rating a heat exchanger (ε-ntu)`,
  `real-gas properties with a cubic eos`,
  `si engine cycle (wiebe heat release)`,
  `supersonic nozzle with a normal shock`,
  `vapor-compression refrigeration cycle`,
  `friction_factor`,
  `minor_loss`,
  `reynolds`,
  `compressibility`,
  `compressibilityfactor`,
  `conductivity`,
  `cp`,
  `cv`,
  `density`,
  `dewpoint`,
  `enthalpy`,
  `entropy`,
  `gibbs`,
  `humrat`,
  `intenergy`,
  `prandtl`,
  `pressure`,
  `quality`,
  `relhum`,
  `soundspeed`,
  `specheat`,
  `temperature`,
  `viscosity`,
  `volexpcoef`,
  `volume`,
  `wetbulb`,
  `dp_1phase`,
  `dp_2phase`,
  `dp_2phase_avg`,
  `dp_compact_core`,
  `dp_gravity`,
  `dp_mueller_steinhagen`,
  `f_fin`,
  `fin_efficiency`,
  `heisler_q`,
  `heisler_temp`,
  `htc_1phase`,
  `htc_cond`,
  `htc_evap`,
  `htc_extair`,
  `hx_aconv`,
  `hx_area_direct`,
  `hx_area_indirect`,
  `hx_dh`,
  `hx_effectiveness`,
  `hx_eta_surf`,
  `hx_fin_len`,
  `hx_ntu`,
  `hx_sigma`,
  `j_fin`,
  `lmtd`,
  `mass_flux`,
  `nu_blend`,
  `nu_churchill_chu`,
  `nu_colburn`,
  `nu_gungor_winterton`,
  `nu_hilpert`,
  `nu_plate`,
  `nu_traviss`,
  `nu_tubebank`,
  `nu_zukauskas`,
  `ua_hx`,
  `viewfactor_disks`,
  `viewfactor_perp`,
  `viewfactor_plates`,
  `dtable`,
  `dtable1`,
  `interpolate`,
  `interpolate1`,
  `interpolate2d`,
  `lookup`,
  `lookuprow`,
  `nlookuprows`,
  `if`,
  `abs`,
  `acos`,
  `arccos`,
  `arccosh`,
  `arcsin`,
  `arcsinh`,
  `arctan`,
  `arctanh`,
  `arrayelmt`,
  `asin`,
  `atan`,
  `atan2`,
  `axpy`,
  `baseconvert`,
  `bitand`,
  `bitnot`,
  `bitor`,
  `bitshiftl`,
  `bitshiftr`,
  `bitxor`,
  `cbrt`,
  `ceil`,
  `cos`,
  `cosh`,
  `cross`,
  `determinant`,
  `dot`,
  `exp`,
  `eye`,
  `factorial`,
  `floor`,
  `gcd`,
  `gemm`,
  `gemv`,
  `inverse`,
  `lcm`,
  `linspace`,
  `ln`,
  `log10`,
  `log2`,
  `mod`,
  `ones`,
  `product`,
  `round`,
  `sign`,
  `sin`,
  `sinh`,
  `solvelinear`,
  `sqrt`,
  `tan`,
  `tanh`,
  `trunc`,
  `zeros`,
  `cholesky`,
  `cond`,
  `det`,
  `diag`,
  `eig`,
  `eigen`,
  `eigenvalues`,
  `eigvec`,
  `eulerrotate`,
  `inv`,
  `ludecompose`,
  `matexp`,
  `norm`,
  `qr`,
  `rank`,
  `svd`,
  `trace`,
  `transpose`,
  `finalvalue`,
  `maxvalue`,
  `minvalue`,
  `odeavg`,
  `odemax`,
  `odemin`,
  `odestddev`,
  `odesum`,
  `odevalue`,
  `timeat`,
  `iso6358`,
  `eos_density`,
  `eos_enthalpy`,
  `eos_entropy`,
  `eos_pressure`,
  `eos_psat`,
  `eos_volume`,
  `eos_z`,
  `c_`,
  `e_`,
  `k_`,
  `nu_`,
  `rho_`,
  `besseli`,
  `besseli0`,
  `besseli1`,
  `besselj`,
  `besselj0`,
  `besselj1`,
  `besselk`,
  `besselk0`,
  `besselk1`,
  `bessely`,
  `bessely0`,
  `bessely1`,
  `beta`,
  `chebyshevt`,
  `chebyshevu`,
  `digamma`,
  `erf`,
  `erfc`,
  `erfinv`,
  `gamma`,
  `hermiteh`,
  `laguerrel`,
  `legendrep`,
  `loggamma`,
  `average`,
  `chi_square`,
  `intercept`,
  `max`,
  `mean`,
  `median`,
  `min`,
  `normalcdf`,
  `normalinvcdf`,
  `normalpdf`,
  `percentile`,
  `probability`,
  `r2`,
  `randg`,
  `random`,
  `rms`,
  `slope`,
  `std`,
  `sum`,
  `var`,
  `stringlen`,
  `stringpos`,
  `stringval`,
  `integralvalue`,
  `nparametricruns`,
  `tableavg`,
  `tablemax`,
  `tablemin`,
  `tablerun#`,
  `tablestddev`,
  `tablesum`,
  `tablevalue`,
  `chen_f`,
  `chen_s`,
  `friedel_phi2`,
  `lm_martinelli_tt`,
  `lm_phi2`,
  `momentum_flux`,
  `nu_cavallini_zecchin`,
  `nu_dittus_boelter`,
  `nu_gnielinski`,
  `nu_shah`,
  `void_homogeneous`,
  `void_rouhani`,
  `void_zivi`,
  `zone_ramp`
];
