//! `FRAUX1` auxiliary property grids — the three surfaces the D1 `(P,h)` split
//! table deliberately cannot carry.
//!
//! [`SaturationSplitTable`](super::satsplit::SaturationSplitTable) tabulates a
//! fluid *with a saturation dome* in `(P,h)`, and stores `T`, `Dmass` and
//! `Smass` on it. Three things a document routinely asks for fall outside that:
//!
//! * **Incompressibles.** `INCOMP::MEG[x]` / `INCOMP::MPG[x]` — the aqueous
//!   glycols an `EG50` coolant loop is written in — have no dome at all, so the
//!   split geometry does not apply to them in the first place.
//! * **Single-phase transport at `(P,T)`.** `htc_extair` asks for `viscosity`,
//!   `conductivity` and `Cpmass` of air, which is not tabulated at all.
//! * **Saturated transport.** `htc_evap`, `htc_cond` and `dp_2phase` ask for the
//!   same three at `Q = 0` and `Q = 1` — and, crucially, *only* there. Not one
//!   of them ever looks up transport off the dome. That is why this costs
//!   ~14 KB per fluid instead of the ~256 KB a second full plane set would.
//!
//! All three are the same shape — a rectangular grid of named outputs over two
//! axes — so they are one format and one reader, generated by `tools/aux-gen`.
//! The binary layout is documented in `tools/aux-gen/README.md`; this module is
//! its only consumer.
//!
//! # The ragged second axis
//!
//! A glycol's valid temperature band depends on its concentration: MEG freezes
//! at 273.5 K as pure water and at 222 K at 60 % mass. A rectangular `(x, T)`
//! grid over the union of those bands would be mostly holes, so the second axis
//! is **normalized** — `tau = (T - Tmin(x)) / (Tmax(x) - Tmin(x))` — with the
//! endpoints stored per column. Every node is then a real state. It is the same
//! trick, for the same reason, that D1 already uses for the liquid piece.
//!
//! # Interpolation
//!
//! Bilinear, in the *stored* space. An output declared `log` is stored as
//! `ln(value)` and exponentiated after interpolation, because viscosity spans
//! decades across a glycol's band and interpolating it linearly is what makes an
//! otherwise-fine grid bad.
//!
//! A query outside the grid is **declined**, never extrapolated: these tables
//! back a Newton solver that probes with whatever the previous iterate produced,
//! and an extrapolated transport property is a wrong number wearing the shape of
//! a right one.

use crate::diag::{FreesError, Result};
// Shared with `satsplit`: both artifacts come out of the same generators, so
// both decoders read them the same way, in one place.
use crate::props::leread::{
    f64_at as read_f64, u16_at as read_u16, u32_at as read_u32, widened_block as read_block,
};

/// Format identifier at byte 0 of every `.fraux`.
const AUX_MAGIC: &[u8; 8] = b"FRAUX1\0\0";
/// Bytes before the variable-length name block.
const AUX_HEADER_FIXED: usize = 84;
/// `flags` bit 0 — axis 2 is normalized, with per-column endpoints.
const AUX_RAGGED: u8 = 1;

/// Which surface a grid describes. Serialized as `u32 kind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AuxKind {
    /// `(mass fraction, normalized T)` for an `INCOMP::` family.
    Incompressible,
    /// `(ln P, T)` single-phase properties.
    PressureTemperature,
    /// `(ln P, Q)` with `Q` exactly `{0, 1}` — properties on the dome.
    SaturationLine,
}

/// How a stored number relates to the value it represents.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Transform {
    Linear,
    Log,
}

/// One tabulated output: its CoolProp name and its storage transform.
#[derive(Debug, Clone)]
struct AuxOutput {
    name: String,
    transform: Transform,
}

/// A decoded `FRAUX1` grid.
#[derive(Debug, Clone)]
pub struct AuxTable {
    name: String,
    kind: AuxKind,
    axis1: Vec<f64>,
    axis2: Vec<f64>,
    /// Ragged only: the real axis-2 endpoints of each axis-1 column.
    axis2_lo: Vec<f64>,
    axis2_hi: Vec<f64>,
    ref_pressure: f64,
    outputs: Vec<AuxOutput>,
    /// One plane per output, axis-1 outer / axis-2 inner, in stored space.
    planes: Vec<Vec<f64>>,
}

impl AuxTable {
    /// The fluid or family this grid serves — `INCOMP::MEG`, `Air`, `R134a`.
    pub fn name(&self) -> &str {
        &self.name
    }

    /// Which of the three surfaces this is.
    pub fn kind(&self) -> AuxKind {
        self.kind
    }

    /// The pressure the `Hmass` / `Smass` columns are stored at.
    ///
    /// Carried in the file rather than agreed by convention: the reader adds
    /// `dHmass_dP * (P - ref)` to it, so a wrong reference would offset every
    /// glycol enthalpy by a constant — silently, and only for glycols.
    pub fn ref_pressure(&self) -> f64 {
        self.ref_pressure
    }

    /// Position of `output` in this grid, by CoolProp name, or `None`.
    pub fn output(&self, name: &str) -> Option<usize> {
        self.outputs.iter().position(|o| o.name == name)
    }

    /// The inclusive axis-1 span, in the axis's own units (log-pressure where
    /// the axis is a log-pressure).
    pub fn axis1_span(&self) -> (f64, f64) {
        (self.axis1[0], self.axis1[self.axis1.len() - 1])
    }

    /// The real axis-2 band at `a1`, for a ragged grid: the endpoints of the
    /// two bracketing columns, linearly blended.
    ///
    /// `None` when the grid is not ragged or `a1` is outside it.
    pub fn band_at(&self, a1: f64) -> Option<(f64, f64)> {
        if self.axis2_lo.is_empty() {
            return None;
        }
        let (i, f) = self.bracket(&self.axis1, a1)?;
        Some((
            lerp(self.axis2_lo[i], self.axis2_lo[i + 1], f),
            lerp(self.axis2_hi[i], self.axis2_hi[i + 1], f),
        ))
    }

    /// `output[k](a1, a2)` by bilinear interpolation, or `None` outside the
    /// grid.
    ///
    /// `a2` is the *stored* second coordinate — normalized `tau` on a ragged
    /// grid, the real value otherwise. Use [`AuxTable::band_at`] to convert.
    pub fn value(&self, k: usize, a1: f64, a2: f64) -> Option<f64> {
        let plane = self.planes.get(k)?;
        let (i, fi) = self.bracket(&self.axis1, a1)?;
        let (j, fj) = self.bracket(&self.axis2, a2)?;
        let n2 = self.axis2.len();
        let v = lerp(
            lerp(plane[i * n2 + j], plane[i * n2 + j + 1], fj),
            lerp(plane[(i + 1) * n2 + j], plane[(i + 1) * n2 + j + 1], fj),
            fi,
        );
        let out = match self.outputs[k].transform {
            Transform::Linear => v,
            Transform::Log => libm::exp(v),
        };
        out.is_finite().then_some(out)
    }

    /// Index of the cell containing `v` and the fraction across it, or `None`
    /// when `v` is outside the axis.
    ///
    /// A non-finite `v` is refused here rather than carried: this is reached
    /// from inside a Newton residual, where the previous iterate can be
    /// anything at all.
    fn bracket(&self, axis: &[f64], v: f64) -> Option<(usize, f64)> {
        if !v.is_finite() || axis.len() < 2 {
            return None;
        }
        let (lo, hi) = (axis[0], axis[axis.len() - 1]);
        if v < lo || v > hi {
            return None;
        }
        // Binary search rather than a divide: the tau axis is deliberately
        // non-uniform (clustered at the cold end, where a glycol's viscosity
        // turns over) and the pressure axes are log-spaced.
        let mut a = 0usize;
        let mut b = axis.len() - 1;
        while b - a > 1 {
            let mid = (a + b) / 2;
            if axis[mid] <= v {
                a = mid;
            } else {
                b = mid;
            }
        }
        let span = axis[a + 1] - axis[a];
        let f = if span > 0.0 {
            (v - axis[a]) / span
        } else {
            0.0
        };
        Some((a, f.clamp(0.0, 1.0)))
    }

    /// Decodes one `FRAUX1` file.
    ///
    /// A malformed artifact is an error, not a panic: these bytes can come from
    /// a regenerated `tools/aux-gen` run or from a host that fetched a grid at
    /// runtime, and a build whose tables do not load should say so rather than
    /// abort a wasm module.
    pub fn decode(bytes: &[u8]) -> Result<AuxTable> {
        if bytes.len() < AUX_HEADER_FIXED {
            return Err(bad_aux(format!(
                "need at least {AUX_HEADER_FIXED} header bytes, found {}",
                bytes.len()
            )));
        }
        if &bytes[0..8] != AUX_MAGIC {
            return Err(bad_aux(
                "bad magic — this is not a FRAUX1 auxiliary property grid",
            ));
        }
        let version = read_u16(bytes, 8);
        if version != 1 {
            return Err(bad_aux(format!(
                "format_version {version} is not 1; this build reads FRAUX1 version 1 only"
            )));
        }
        let elem_f32 = match bytes[10] {
            0 => false,
            1 => true,
            other => {
                return Err(bad_aux(format!(
                    "elem_kind {other} is neither 0 (f64) nor 1 (f32)"
                )))
            }
        };
        let flags = bytes[11];
        if flags & !AUX_RAGGED != 0 {
            return Err(bad_aux(format!(
                "flags {flags:#04x} set bits this format version reserves"
            )));
        }
        let ragged = flags & AUX_RAGGED != 0;
        let kind = match read_u32(bytes, 12) {
            0 => AuxKind::Incompressible,
            1 => AuxKind::PressureTemperature,
            2 => AuxKind::SaturationLine,
            other => return Err(bad_aux(format!("kind {other} is not one this build knows"))),
        };
        let n1 = read_u32(bytes, 16) as usize;
        let n2 = read_u32(bytes, 20) as usize;
        let n_out = read_u32(bytes, 24) as usize;
        let header_bytes = read_u32(bytes, 28) as usize;
        if n1 < 2 || n2 < 2 {
            return Err(bad_aux(format!(
                "a grid needs at least 2x2 samples, header says {n1}x{n2}"
            )));
        }
        if n_out == 0 || n_out > 64 {
            return Err(bad_aux(format!("n_outputs {n_out} is outside [1, 64]")));
        }
        if header_bytes < AUX_HEADER_FIXED || header_bytes > bytes.len() {
            return Err(bad_aux(format!(
                "header_bytes {header_bytes} is outside [{AUX_HEADER_FIXED}, {}]",
                bytes.len()
            )));
        }
        let ref_pressure = read_f64(bytes, 64);

        let name_len = read_u16(bytes, 72) as usize;
        let cpver_len = read_u16(bytes, 74) as usize;
        let a1_len = read_u16(bytes, 76) as usize;
        let a2_len = read_u16(bytes, 78) as usize;

        let mut at = AUX_HEADER_FIXED;
        let name = take_str(bytes, &mut at, name_len, header_bytes, "name")?;
        let _cpver = take_str(bytes, &mut at, cpver_len, header_bytes, "coolprop_version")?;
        let _a1 = take_str(bytes, &mut at, a1_len, header_bytes, "axis1_name")?;
        let _a2 = take_str(bytes, &mut at, a2_len, header_bytes, "axis2_name")?;

        let mut outputs = Vec::with_capacity(n_out);
        for k in 0..n_out {
            if at + 2 > header_bytes {
                return Err(bad_aux(format!("output {k} runs past the header")));
            }
            let len = read_u16(bytes, at) as usize;
            at += 2;
            let oname = take_str(bytes, &mut at, len, header_bytes, "output name")?;
            if at >= header_bytes {
                return Err(bad_aux(format!("output {k} has no transform byte")));
            }
            let transform = match bytes[at] {
                0 => Transform::Linear,
                1 => Transform::Log,
                other => {
                    return Err(bad_aux(format!(
                        "output '{oname}' has transform {other}, which is neither 0 (linear) nor 1 (log)"
                    )))
                }
            };
            at += 1;
            outputs.push(AuxOutput {
                name: oname,
                transform,
            });
        }

        // Payload: axes, then the ragged endpoint columns, then one plane per
        // output. Every length is checked before it is read.
        // Checked throughout. `usize` is 32 bits on wasm32, and `n1`/`n2` come
        // straight off the wire as `u32`, so a hostile header can make this
        // product wrap to a small number that passes the length check below and
        // then indexes off the end in `read_block`. That would be a panic, and
        // this module's contract is that a malformed artifact is a `Result`.
        let width = if elem_f32 { 4usize } else { 8usize };
        let ragged_cols = if ragged { 2 * n1 } else { 0 };
        let want = n1
            .checked_mul(n2)
            .and_then(|cells| cells.checked_mul(n_out))
            .and_then(|nodes| nodes.checked_add(n1))
            .and_then(|nodes| nodes.checked_add(n2))
            .and_then(|nodes| nodes.checked_add(ragged_cols))
            .and_then(|nodes| nodes.checked_mul(width))
            .ok_or_else(|| {
                bad_aux(format!(
                    "declares {n1}x{n2} with {n_out} outputs, whose payload size does not fit \
                     in this target's address space"
                ))
            })?;
        let have = bytes.len() - header_bytes;
        if have < want {
            return Err(bad_aux(format!(
                "declares {n1}x{n2} with {n_out} outputs ({want} payload bytes), found {have}"
            )));
        }

        let mut at = header_bytes;
        let axis1 = read_block(bytes, &mut at, n1, elem_f32);
        let axis2 = read_block(bytes, &mut at, n2, elem_f32);
        let (axis2_lo, axis2_hi) = if ragged {
            let lo = read_block(bytes, &mut at, n1, elem_f32);
            let hi = read_block(bytes, &mut at, n1, elem_f32);
            (lo, hi)
        } else {
            (Vec::new(), Vec::new())
        };
        let mut planes = Vec::with_capacity(n_out);
        for _ in 0..n_out {
            planes.push(read_block(bytes, &mut at, n1 * n2, elem_f32));
        }

        // A non-monotonic axis would make the binary search return nonsense
        // rather than fail, so it is rejected at load.
        // `all(>)` rather than `any(!>)` so a NaN node fails the check instead
        // of passing it — a NaN compares false either way, and only one of the
        // two spellings turns that into a rejection.
        for (label, axis) in [("axis1", &axis1), ("axis2", &axis2)] {
            if !axis.windows(2).all(|w| w[1] > w[0]) {
                return Err(bad_aux(format!("{label} is not strictly increasing")));
            }
        }
        if ragged && !axis2_lo.iter().zip(&axis2_hi).all(|(l, h)| h > l) {
            return Err(bad_aux("a ragged column has an empty axis-2 band"));
        }
        if kind == AuxKind::Incompressible && (!ref_pressure.is_finite() || ref_pressure <= 0.0) {
            return Err(bad_aux(
                "an incompressible grid needs a positive ref_pressure",
            ));
        }

        Ok(AuxTable {
            name,
            kind,
            axis1,
            axis2,
            axis2_lo,
            axis2_hi,
            ref_pressure,
            outputs,
            planes,
        })
    }
}

fn lerp(a: f64, b: f64, f: f64) -> f64 {
    a + (b - a) * f
}

fn bad_aux(msg: impl Into<String>) -> FreesError {
    FreesError::property(format!("generated aux property grid: {}", msg.into()))
}

fn take_str(bytes: &[u8], at: &mut usize, len: usize, limit: usize, what: &str) -> Result<String> {
    if *at + len > limit {
        return Err(bad_aux(format!("{what} runs past the header")));
    }
    let s = core::str::from_utf8(&bytes[*at..*at + len])
        .map_err(|_| bad_aux(format!("{what} is not UTF-8")))?
        .to_string();
    *at += len;
    Ok(s)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::props::tables;

    #[test]
    fn the_linked_grids_decode_at_the_geometry_aux_gen_chose() {
        let meg = AuxTable::decode(tables::MEG_FRAUX).expect("meg decodes");
        assert_eq!(meg.name(), "INCOMP::MEG");
        assert_eq!(meg.kind(), AuxKind::Incompressible);
        // Every concentration the language can spell is a node, not an
        // interpolation — that is the whole accuracy argument.
        let (lo, hi) = meg.axis1_span();
        assert_eq!(lo, 0.0);
        // f32 storage, so 0.60 arrives as 0.6000000238... — compare as the
        // stored precision, not as an exact decimal.
        assert!((hi - 0.60).abs() < 1e-6, "{hi}");
        assert!(meg.ref_pressure() > 0.0);
        for want in [
            "Dmass",
            "Cpmass",
            "viscosity",
            "conductivity",
            "Hmass",
            "Smass",
            "dHmass_dP",
            "dSmass_dP",
        ] {
            assert!(meg.output(want).is_some(), "{want}");
        }

        let air = AuxTable::decode(tables::AIR_FRAUX).expect("air decodes");
        assert_eq!(air.kind(), AuxKind::PressureTemperature);
        assert!(air.band_at(12.0).is_none(), "air is not ragged");

        let sat = AuxTable::decode(tables::R134A_SAT_FRAUX).expect("r134a sat decodes");
        assert_eq!(sat.kind(), AuxKind::SaturationLine);
    }

    /// The tau axis is placed by equidistributing the interpolation error of
    /// `ln(mu)` (`AuxGen.errorEquidistributed`), not uniformly. It must stay
    /// that way: a uniform axis measures ~2x worse on viscosity, and viscosity
    /// is what `htc_1phase` amplifies hardest.
    #[test]
    fn the_tau_axis_is_non_uniform_and_denser_at_the_cold_end() {
        let meg = AuxTable::decode(tables::MEG_FRAUX).unwrap();
        assert_eq!(meg.axis2[0], 0.0);
        assert!((meg.axis2[meg.axis2.len() - 1] - 1.0).abs() < 1e-6);
        let first = meg.axis2[1] - meg.axis2[0];
        let last = meg.axis2[meg.axis2.len() - 1] - meg.axis2[meg.axis2.len() - 2];
        assert!(
            first < last,
            "cold end must be the denser one: {first} vs {last}"
        );
        // Strictly increasing is load-bearing for the reader's binary search.
        assert!(meg.axis2.windows(2).all(|w| w[1] > w[0]));
    }

    /// Off-grid queries decline instead of extrapolating — this reader is
    /// reached from inside a Newton residual.
    #[test]
    fn a_query_outside_the_grid_is_declined_not_extrapolated() {
        let meg = AuxTable::decode(tables::MEG_FRAUX).unwrap();
        let d = meg.output("Dmass").unwrap();
        assert!(meg.value(d, 0.5, 0.5).is_some());
        assert!(meg.value(d, 0.5, 1.5).is_none(), "tau above the band");
        assert!(meg.value(d, 0.5, -0.1).is_none(), "tau below the band");
        assert!(
            meg.value(d, 0.9, 0.5).is_none(),
            "90 % glycol is not tabulated"
        );
        assert!(meg.value(d, f64::NAN, 0.5).is_none());
        assert!(meg.value(d, 0.5, f64::NAN).is_none());
        assert!(meg.value(99, 0.5, 0.5).is_none(), "no such output");
    }

    /// Garbage in is a `Result`, never a panic.
    #[test]
    fn a_hostile_byte_string_is_refused_rather_than_trusted() {
        for bad in [
            &b""[..],
            &b"FRAUX1\0\0"[..],
            &b"FRPHTAB1 wrong format entirely"[..],
            &[0xffu8; 300][..],
        ] {
            assert!(AuxTable::decode(bad).is_err(), "{bad:?}");
        }
        let truncated = &tables::MEG_FRAUX[..tables::MEG_FRAUX.len() / 2];
        let err = AuxTable::decode(truncated).unwrap_err().to_string_message();
        assert!(err.contains("declares"), "{err}");

        let mut flipped = tables::MEG_FRAUX.to_vec();
        flipped[10] = 7; // elem_kind
        let err = AuxTable::decode(&flipped).unwrap_err().to_string_message();
        assert!(err.contains("elem_kind"), "{err}");

        let mut flipped = tables::MEG_FRAUX.to_vec();
        flipped[12] = 9; // kind
        let err = AuxTable::decode(&flipped).unwrap_err().to_string_message();
        assert!(err.contains("kind"), "{err}");

        // A header whose declared grid overflows the address space must come
        // back as an error, not a panic. `usize` is 32 bits on wasm32, so this
        // is reachable there with values a `u32` field can hold.
        let mut huge = tables::MEG_FRAUX.to_vec();
        huge[16..20].copy_from_slice(&u32::MAX.to_le_bytes()); // n1
        huge[20..24].copy_from_slice(&u32::MAX.to_le_bytes()); // n2
        let err = AuxTable::decode(&huge).unwrap_err().to_string_message();
        assert!(!err.is_empty(), "{err}");
    }
}
