import js from '@eslint/js'
import globals from 'globals'
import react from 'eslint-plugin-react'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'

// Flat config (ESLint 9). Lints the TypeScript/React sources. Generated and
// build artifacts are ignored. `docsCatalog.ts` is machine-generated by
// scripts/compile-docs.js, so it is excluded from linting.
export default tseslint.config(
  {
    ignores: [
      'dist',
      'build',
      'node_modules',
      'src/docsCatalog.ts',
      'vite.config.ts',
      'vitest.config.ts',
      'eslint.config.mjs',
      'scripts/**',
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    settings: {
      react: { version: 'detect' },
    },
    plugins: {
      react,
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      // eslint-plugin-react-hooks v7 (React Compiler-era) additions, surfaced
      // as warnings rather than errors: `refs` forbids the latest-props-in-ref
      // pattern this codebase uses deliberately (WorkspaceDock, EquationEditor
      // — a ref updated during render so stable callbacks see current props
      // without resubscribing), and `set-state-in-effect` flags intentional
      // derived-state resets on prop change. Revisit if/when React Compiler
      // is adopted, which requires both to hold strictly.
      'react-hooks/refs': 'warn',
      'react-hooks/set-state-in-effect': 'warn',
      'react-refresh/only-export-components': [
        'warn',
        { allowConstantExport: true },
      ],
      // Surfaced, not blocking — tracked as a separate cleanup task (no-explicit-any).
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      // Intentional empty catch blocks are fallbacks (localStorage/JSON guards).
      'no-empty': ['error', { allowEmptyCatch: true }],
      // Enabled (as a warning) so the codebase's existing inline disables for it
      // resolve; index keys are acceptable in the few flagged static lists.
      'react/no-array-index-key': 'warn',
    },
  },
  {
    // Test files additionally see Vitest/Node globals.
    files: ['**/*.{test,spec}.{ts,tsx}', 'src/test/**'],
    languageOptions: {
      globals: { ...globals.node },
    },
  },
)
